---
# tasks file for kube_master
  - name: Turn off swap
    command: swapoff -a

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Disable Firewall
    systemd: name=firewalld state=stopped enabled=no

  - name: Update yum
    yum: name=* state=latest update_cache=yes

  - name: Update yum
    yum: name={{ item }} state=present
    with_items:
      - lsof
      - net-tools

  - name: Install docker
    yum: name=docker state=present

  - name: Start docker
    service: name=docker state=started enabled=yes

  - name: Add Kubernetes repository
    yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repo
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Install Kubernetes
    yum: name={{ item }} state=latest update_cache=yes
    with_items:
      - kubelet
      - kubeadm
      - kubectl

  - name: Start Kubernetes Service
    service: name=kubelet  state=started enabled=yes
